/* ============================================================
   LEAKEPEDIA — Forensic National Incident Dataset (2002–2026)
   "The Public Ledger of Compromised Examinations in India"
   
   Compiled from public records: Wikipedia master list, national
   investigative dailies, High Court and Supreme Court rulings,
   and official CBI/ED chargesheets.
   ============================================================ */

const WIKI_LIST = {
  label: "Wikipedia — List of paper leaks in India",
  url: "https://en.wikipedia.org/wiki/List_of_paper_leaks_in_India",
};

const INCIDENTS = [
  /* ---------------- 2002 ---------------- */
  {
    id: "e2002-aiims",
    date: "2002-01-06",
    exam: "AIIMS Post-Graduate Medical Entrance 2002",
    body: "All India Institute of Medical Sciences",
    state: "All India",
    region: "All-India",
    type: "Medical entrance",
    status: "Probe ordered",
    scale: "Papers sold for ₹75,000–₹1,00,000 per candidate",
    summary: "Investigation revealed widespread circulation of question papers in Patna and Lucknow prior to the national medical postgraduate test, triggering a Delhi High Court directive for a Central Bureau of Investigation probe.",
    detail: "On the eve of the premier medical institution's postgraduate entrance examination, organized tout networks in Bihar and Uttar Pradesh distributed advance copies of question papers across designated transit points.\n\nFollowing public interest petitions highlighting anomalous scores and identical answer keys among clusters of examinees in northern centres, the Delhi High Court ordered the CBI to take over the criminal investigation.\n\nThe probe established an early blueprint of inter-state paper syndicates targeting elite medical seats through compromised testing conduits.",
    keyFacts: [
      { k: "Modus Operandi", v: "Inter-state tout network operating via Patna and Lucknow hubs" },
      { k: "Price per Seat", v: "₹75,000 to ₹1,00,000" },
      { k: "Judicial Action", v: "Delhi High Court directed CBI central inquiry" },
      { k: "Outcome", v: "Structural overhaul of PG question paper dispatch protocols" }
    ],
    sources: [WIKI_LIST],
  },
  {
    id: "e2002-rrb-asm",
    date: "2002-08-18",
    exam: "RRB Probationary Assistant Station Master 2002",
    body: "Railway Recruitment Board, Mumbai",
    state: "All India",
    region: "All-India",
    type: "Recruitment",
    status: "Convictions",
    scale: "Papers sold for ₹50,000–₹1,00,000; 8 officials convicted",
    summary: "A leak syndicate involving Western Railway insiders compromised the recruitment test. Following a CBI investigation, eight former railway employees were convicted and sentenced to five years in prison.",
    detail: "Railway recruitment across western zones was disrupted after question sheets for station master posts were leaked hours prior to testing by an insider-tout nexus.\n\nThe Western Railway cancelled the compromised examination rounds, and the CBI filed detailed chargesheets establishing bribery, document theft, and illicit distribution.\n\nIn a historic judicial conclusion in July 2025, a special CBI court in Ahmedabad awarded five-year rigorous imprisonment terms to eight former Western Railway employees.",
    keyFacts: [
      { k: "Agency", v: "Central Bureau of Investigation (CBI)" },
      { k: "Conviction", v: "8 Western Railway personnel sentenced to 5 years (July 2025)" },
      { k: "Recovery", v: "Cash, candidate lists, and matching question sets" }
    ],
    sources: [WIKI_LIST],
  },

  /* ---------------- 2003 ---------------- */
  {
    id: "e2003-cat",
    date: "2003-11-23",
    exam: "Common Admission Test (CAT) 2003",
    body: "Indian Institutes of Management",
    state: "All India",
    region: "All-India",
    type: "Management entrance",
    status: "Cancelled & retest",
    scale: "Nationwide cancellation; papers sold for ₹2–4 lakh",
    summary: "The CBI intercepted leaked CAT question papers and answer keys from a hotel in Delhi the night before the examination, compelling the IIM directors to cancel the entire test nationwide.",
    detail: "In one of the most high-profile admissions breaches of the decade, the CBI raided a hotel in New Delhi on the eve of the CAT examination, arresting four key individuals, including medical practitioners operating as professional paper brokers.\n\nConfiscated materials matched the live question papers slated for distribution across the country the following morning.\n\nThe directors of all six Indian Institutes of Management convened in an emergency meeting and ordered a complete national cancellation. A retest was successfully held on February 15, 2004 under heightened military-grade security.",
    keyFacts: [
      { k: "Affected Institutions", v: "All IIMs (Ahmedabad, Bangalore, Calcutta, Lucknow, Indore, Kozhikode)" },
      { k: "Price per Paper", v: "₹2,00,000 to ₹4,00,000" },
      { k: "Investigation", v: "Raid conducted by CBI Special Crime Branch" },
      { k: "Retest Date", v: "February 15, 2004" }
    ],
    sources: [WIKI_LIST],
  },

  /* ---------------- 2004 ---------------- */
  {
    id: "e2004-rrb-groupd",
    date: "2004-01-04",
    exam: "RRB Group-D Recruitment 2004",
    body: "Railway Recruitment Board, Patna",
    state: "All India",
    region: "All-India",
    type: "Recruitment",
    status: "Cancelled & retest",
    scale: "2.76 lakh candidates; 10,000 gangman posts",
    summary: "Massive recruitment for 10,000 track maintainer and gangman posts was cancelled across eastern zones after handwritten question drafts seized by the CBI were proven to match the official question papers.",
    detail: "Over 2.76 lakh aspirants sitting for Group-D railway recruitment across Bihar, West Bengal, and Uttar Pradesh were left in limbo after evidence of a systemic leak emerged from eastern zonal distribution centres.\n\nThe CBI produced handwritten question copies seized from coaching hideouts hours before exam commencement, establishing exact matches with the official printed sets.\n\nIndian Railways immediately nullified the examinations and mandated decentralized re-testing across zonal recruitment boards.",
    keyFacts: [
      { k: "Vacancies", v: "10,000 Gangman and Trackman positions" },
      { k: "Aspirants Affected", v: "276,000 candidates" },
      { k: "Jurisdiction", v: "Patna, Kolkata, and Allahabad RRB zones" }
    ],
    sources: [WIKI_LIST],
  },
  {
    id: "e2004-aipmt",
    date: "2004-04-11",
    exam: "AIPMT / CBSE-PMT 2004",
    body: "Central Board of Secondary Education",
    state: "All India",
    region: "All-India",
    type: "Medical entrance",
    status: "Cancelled & retest",
    scale: "Nationwide cancellation; papers leaked 10–14 hours prior",
    summary: "Physics and Chemistry sections were leaked in Delhi 10 to 14 hours ahead of the All-India Pre-Medical Test. CBSE cancelled the national test and the Union HRD Ministry ordered a full CBI investigation.",
    detail: "Hours before hundreds of thousands of medical aspirants entered test halls across India, Delhi Police and intelligence units uncovered widespread circulation of complete Physics and Chemistry question sheets.\n\nForensic verification with CBSE authorities confirmed an exact match with the confidential examination master sets.\n\nUnion Minister of Human Resource Development intervened to announce a total cancellation. A comprehensive retest was scheduled, and the CBI subsequently dismantled an inter-state syndicate with ties to coaching centres and printing presses.",
    keyFacts: [
      { k: "Lead Time of Breach", v: "10 to 14 hours prior to exam morning" },
      { k: "Scope", v: "All India Pre-Medical / Pre-Dental Entrance Examination" },
      { k: "Action Taken", v: "CBI central investigation and emergency national re-examination" }
    ],
    sources: [WIKI_LIST],
  },

  /* ---------------- 2006 ---------------- */
  {
    id: "e2006-hpcpmt",
    date: "2006-06-01",
    exam: "HP-CPMT 2006",
    body: "Himachal Pradesh University",
    state: "Himachal Pradesh",
    region: "North",
    type: "Medical entrance",
    status: "Arrests & FIR",
    scale: "₹7 lakh tout payment intercepted; printing press nexus",
    summary: "State police exposed a network linking university examination coordinators with a Lucknow printing press, intercepting post-dated cheques worth ₹7 lakh intended to guarantee MBBS seats.",
    sources: [WIKI_LIST],
  },

  /* ---------------- 2007 ---------------- */
  {
    id: "e2007-icai",
    date: "2007-08-05",
    exam: "ICAI CA Common Proficiency Test 2007",
    body: "Institute of Chartered Accountants of India",
    state: "All India",
    region: "All-India",
    type: "Professional",
    status: "Convictions",
    scale: "Broadcast via TV sting operation; convictions upheld in 2022",
    summary: "Sealed question packets were prematurely unsealed and sold at a Delhi examination centre. A television sting operation exposed the racket, resulting in convictions of the centre superintendent and staff.",
    sources: [WIKI_LIST],
  },

  /* ---------------- 2008 ---------------- */
  {
    id: "e2008-npsc",
    date: "2008-09-01",
    exam: "NPSC Civil & Police Services (Main) 2008",
    body: "Nagaland Public Service Commission",
    state: "Nagaland",
    region: "Northeast",
    type: "Civil services",
    status: "Results nullified",
    scale: "11 selections quashed; commission staff suspended",
    summary: "The commission detected internal script-swapping and grade tampering. An Assistant Superintendent was suspended, 11 fraudulent results were nullified, and state vigilance filed criminal cases.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2008-vyapam-patwari",
    date: "2008-09-07",
    exam: "Vyapam Patwari Recruitment 2008",
    body: "MP Professional Examination Board (Vyapam)",
    state: "Madhya Pradesh",
    region: "West",
    type: "Recruitment",
    status: "Convictions",
    scale: "10 individuals sentenced to 5 years rigorous imprisonment",
    summary: "Fraudulent scorecards and forged eligibility certificates were manufactured by board insiders to award revenue officer positions, forming one of the earliest documented pillars of the Vyapam saga.",
    detail: "During the 2008 revenue patwari recruitment cycle, middlemen in collusive agreement with MPPEB officials systematically swapped evaluated OMR responses and issued fabricated eligibility documents.\n\nThe fraud emerged during department verification audits, revealing candidates with zero qualifying background holding merit ranks.\n\nIn December 2025, a dedicated CBI Special Court concluded trials against the syndicate, sentencing 10 individuals, including middlemen and beneficiaries, to five years of rigorous imprisonment.",
    keyFacts: [
      { k: "Scam Architecture", v: "Direct OMR score fabrication and forged qualification credentials" },
      { k: "Trial Conclusion", v: "CBI Court sentenced 10 accused in December 2025" },
      { k: "Context", v: "Early phase of the multi-tiered Madhya Pradesh Vyapam scam" }
    ],
    sources: [
      WIKI_LIST,
      { label: "Wikipedia — Vyapam scam", url: "https://en.wikipedia.org/wiki/Vyapam_scam" },
    ],
  },
  {
    id: "e2008-rrb-alld",
    date: "2008-12-14",
    exam: "RRB Recruitment (Allahabad zone) 2008",
    body: "Railway Recruitment Board, Allahabad",
    state: "All India",
    region: "All-India",
    type: "Recruitment",
    status: "Cancelled & retest",
    scale: "~37,000 candidates affected; 270+ candidates detained",
    summary: "UP Special Task Force raided examination centres hours before test time, arresting syndicate kingpin Bedi Ram and detaining over 270 candidates caught with leaked question sheets.",
    sources: [WIKI_LIST],
  },

  /* ---------------- 2009 ---------------- */
  {
    id: "e2009-meghalaya",
    date: "2009-02-01",
    exam: "Meghalaya Education Dept Recruitment (White Ink Scam) 2009",
    body: "Meghalaya Education Department",
    state: "Meghalaya",
    region: "Northeast",
    type: "Recruitment",
    status: "Probe ordered",
    scale: "Systemic score alterations using correction fluid",
    summary: "A CBI inquiry substantiated allegations that interview scorecards and written marks for primary school teachers were altered using correction fluid under political direction.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2009-rrb-ajmer",
    date: "2009-02-15",
    exam: "RRB Assistant Station Master 2009 (Ajmer zone)",
    body: "Railway Recruitment Board, Ajmer",
    state: "All India",
    region: "All-India",
    type: "Recruitment",
    status: "Arrests & FIR",
    scale: "109 arrests across three states; test postponed",
    summary: "Simultaneous raids across Jaipur, Bhopal, and Lucknow dismantled an interstate paper leak gang, leading to the immediate postponement of the ASM written examination and 109 arrests.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2009-vyapam-pmt",
    date: "2009-07-08",
    exam: "MP Pre-Medical Test (PMT) 2009",
    body: "MP Professional Examination Board (Vyapam)",
    state: "Madhya Pradesh",
    region: "West",
    type: "Medical entrance",
    status: "Convictions",
    scale: "Organized solver and proxy candidate deployment",
    summary: "The Vyapam medical entrance was subverted by professional 'proxy solvers' paid to sit under fraudulent identities, culminating in December 2024 CBI convictions in Indore.",
    sources: [WIKI_LIST],
  },

  /* ---------------- 2010 ---------------- */
  {
    id: "e2010-uppsc-aps",
    date: "2010-01-01",
    exam: "UPPSC Additional Private Secretary 2010",
    body: "UP Public Service Commission",
    state: "Uttar Pradesh",
    region: "North",
    type: "Civil services",
    status: "Probe ordered",
    scale: "Failed candidates illegally certified and appointed",
    summary: "The CBI registered an FIR and raided former exam controllers after evidence proved candidates failing basic Hindi shorthand tests were awarded official appointments.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2010-rrb-mumbai",
    date: "2010-06-06",
    exam: "RRB Mumbai ALP / ASM Recruitment 2010",
    body: "Railway Recruitment Board, Mumbai",
    state: "All India",
    region: "All-India",
    type: "Recruitment",
    status: "Convictions",
    scale: "1,936 posts; former RRB Chairman convicted",
    summary: "CBI intercepted an organized commercial syndicate led by the sitting RRB Mumbai Chairman S.M. Sharma. In January 2024, a special court sentenced 10 accused to 5 years rigorous imprisonment.",
    detail: "In one of the most conclusive prosecutions of administrative corruption in Indian railways, the CBI unmasked a multi-crore bribery operation headed by sitting RRB Mumbai Chairman S.M. Sharma and his son.\n\nQuestion sets were leaked from confidential custodial storage to commercial brokers who trained prospective candidates at undisclosed hotels prior to test day.\n\nIn January 2024, a special CBI court found Sharma and nine accomplices guilty of criminal conspiracy, document theft, and corruption, handing down five-year rigorous prison sentences.",
    keyFacts: [
      { k: "High-Profile Accused", v: "Former RRB Mumbai Chairman S.M. Sharma" },
      { k: "Judicial Order", v: "10 individuals sentenced to 5 years rigorous imprisonment (Jan 2024)" },
      { k: "Scale", v: "1,936 Assistant Loco Pilot and Station Master vacancies" }
    ],
    sources: [WIKI_LIST],
  },
  {
    id: "e2010-navy-ldc",
    date: "2010-09-26",
    exam: "Navy Western Command LDC Recruitment 2010",
    body: "Indian Navy",
    state: "All India",
    region: "All-India",
    type: "Defence & police",
    status: "Convictions",
    scale: "Confidential master paper exported on USB storage",
    summary: "The President of the Naval Recruitment Board extracted the question paper via USB flash drive. CBI raids intercepted matching copies, leading to convictions in September 2025.",
    sources: [WIKI_LIST],
  },

  /* ---------------- 2011 ---------------- */
  {
    id: "e2011-lic",
    date: "2011-02-27",
    exam: "LIC AAO Recruitment 2011",
    body: "Life Insurance Corporation",
    state: "Delhi",
    region: "North",
    type: "Banking & insurance",
    status: "Cancelled & retest",
    scale: "1.65 lakh candidates; 150 test centres cancelled",
    summary: "Delhi Police busted an interstate syndicate selling leaked papers procured from an EdCIL printing press for ₹5–7 lakh, prompting LIC to cancel testing across 150 centres.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2011-aieee",
    date: "2011-05-01",
    exam: "AIEEE 2011",
    body: "Central Board of Secondary Education",
    state: "All India",
    region: "All-India",
    type: "Engineering entrance",
    status: "Cancelled & retest",
    scale: "~12 lakh candidates; national exam delayed by 3 hours",
    summary: "The All India Engineering Entrance Examination paper leaked in Uttar Pradesh and was sold for ₹6 lakh. CBSE delayed the national exam by three hours to deploy contingency question sets and arranged a special retest.",
    detail: "Over 12 lakh engineering aspirants across the country experienced extreme disruption on May 1, 2011, when intelligence agencies in Lucknow intercepted leaked question papers matching the master set.\n\nIn a frantic emergency operation, CBSE instructed thousands of examination centres nationwide to withhold distribution and deploy reserve contingency paper sets, causing a 3-hour nationwide delay.\n\nCandidates who were unable to take the delayed test due to conflicts with the Armed Forces Medical College entrance were provided an administrative retest on May 11, 2011.",
    keyFacts: [
      { k: "Scale", v: "12 lakh engineering candidates nationwide" },
      { k: "Emergency Measure", v: "3-hour exam postponement to swap with backup paper sets" },
      { k: "Follow-up", v: "Special national retest for overlapping entrance candidates" }
    ],
    sources: [WIKI_LIST],
  },
  {
    id: "e2011-cgpmt",
    date: "2011-06-19",
    exam: "Chhattisgarh PMT 2011",
    body: "CG Professional Examination Board",
    state: "Chhattisgarh",
    region: "West",
    type: "Medical entrance",
    status: "Cancelled & retest",
    scale: "~20,000 registered; 80 aspirants caught in raid",
    summary: "Crime branch officers raided a Bilaspur rest house where approximately 80 candidates were memorizing leaked question papers with answers. The exam was cancelled twice within a single week.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2011-uptet",
    date: "2011-11-13",
    exam: "UP Teacher Eligibility Test 2011",
    body: "UP Secondary Education Board",
    state: "Uttar Pradesh",
    region: "North",
    type: "Teacher eligibility",
    status: "Arrests & FIR",
    scale: "Statewide bribery racket; Secondary Education Director arrested",
    summary: "Candidates paid massive bribes to alter evaluation answer sheets post-exam. State police raided administrative offices in February 2012, arresting the Director of Secondary Education and key aides.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2011-vyapam-samvida",
    date: "2011-12-01",
    exam: "Vyapam Contract Teacher (Samvida Shala Shikshak Varg-3) 2011",
    body: "MP Professional Examination Board (Vyapam)",
    state: "Madhya Pradesh",
    region: "West",
    type: "Teacher eligibility",
    status: "Arrests & FIR",
    scale: "95 individuals chargesheeted including former cabinet minister",
    summary: "The CBI filed comprehensive chargesheets against 95 accused, including former Technical Education Minister Laxmikant Sharma and top Vyapam administrators, for manipulating teacher eligibility scores.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2011-kpsc",
    date: "2011-12-15",
    exam: "KPSC Gazetted Probationers 2011 (Group A & B)",
    body: "Karnataka Public Service Commission",
    state: "Karnataka",
    region: "South",
    type: "Civil services",
    status: "Results nullified",
    scale: "362 selections nullified; 10,521-page CID chargesheet",
    summary: "State CID uncovered rampant bribery and mark tampering across interview stages. A 10,521-page chargesheet was filed against former KPSC Chairman Gonal Bhimappa and officials, nullifying 362 appointments.",
    sources: [WIKI_LIST],
  },

  /* ---------------- 2012 ---------------- */
  {
    id: "e2012-mppsc",
    date: "2012-01-01",
    exam: "MPPSC State Service 2012",
    body: "MP Public Service Commission",
    state: "Madhya Pradesh",
    region: "West",
    type: "Civil services",
    status: "Probe ordered",
    scale: "Interviews and merit selections frozen",
    summary: "Delhi Police Crime Branch smashed an interstate paper leak syndicate targeting state civil service exams, compelling MPPSC to suspend interview procedures pending criminal investigation.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2012-mp-prepg",
    date: "2012-03-11",
    exam: "MP Pre-PG Medical Test 2012",
    body: "MP Professional Examination Board (Vyapam)",
    state: "Madhya Pradesh",
    region: "West",
    type: "Medical entrance",
    status: "Arrests & FIR",
    scale: "Model answer keys sold for postgraduate clinical seats",
    summary: "STF and CBI documented that confidential answer keys were leaked to private coaching rings to guarantee high merit rankings in specialized medical postgraduate seats.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2012-sbi",
    date: "2012-05-27",
    exam: "SBI Assistants Grade Recruitment 2012",
    body: "State Bank of India",
    state: "Delhi",
    region: "North",
    type: "Banking & insurance",
    status: "Arrests & FIR",
    scale: "Covert Bluetooth earpiece transmission network",
    summary: "Delhi Police arrested syndicate operatives led by Ravi Atri hours before test commencement. Solved answer keys were being transmitted to candidates inside halls via concealed micro-Bluetooth transmitters.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2012-jkcet",
    date: "2012-06-01",
    exam: "JK Common Entrance Test (Medical) 2012",
    body: "J&K Board of Professional Entrance Examinations",
    state: "Jammu & Kashmir",
    region: "North",
    type: "Medical entrance",
    status: "Convictions",
    scale: "24 fraudulent beneficiaries; BOPEE Chairman convicted",
    summary: "BOPEE Chairman Mushtaq Ahmad Peer sold medical entrance question papers for ₹60 lakh through touts. State Crime Branch prosecuted the case, resulting in 16-year prison sentences in 2018.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2012-vyapam-pmt",
    date: "2012-06-01",
    exam: "MP Pre-Medical Test 2012 (Vyapam)",
    body: "MP Professional Examination Board (Vyapam)",
    state: "Madhya Pradesh",
    region: "West",
    type: "Medical entrance",
    status: "Arrests & FIR",
    scale: "592 individuals chargesheeted; 4 medical college chairmen",
    summary: "The CBI filed an extensive chargesheet naming 592 accused, including Vyapam officers, solver networks, middlemen, and chairmen of four prominent private medical colleges.",
    detail: "The 2012 Pre-Medical Test in Madhya Pradesh represented the institutional zenith of the Vyapam racket.\n\nMiddlemen booked blocks of examination roll numbers to seat bright solver students directly beside paying beneficiaries, enabling systematic answer copying.\n\nThe CBI's massive investigation culminated in chargesheets against 592 persons, exposing an institutionalized pipeline spanning government bureaucrats, coaching mafias, and private medical college managements.",
    keyFacts: [
      { k: "Accused Roster", v: "592 individuals named in comprehensive CBI chargesheet" },
      { k: "Institutional Link", v: "Four private medical college chairmen indicted" },
      { k: "Technique", v: "Engineered seat allotment (roll-number pairing) and OMR forgery" }
    ],
    sources: [
      WIKI_LIST,
      { label: "Wikipedia — Vyapam scam", url: "https://en.wikipedia.org/wiki/Vyapam_scam" },
    ],
  },
  {
    id: "e2012-pspcl",
    date: "2012-07-29",
    exam: "PSPCL AE / JE Recruitment 2012",
    body: "Punjab State Power Corporation",
    state: "Punjab",
    region: "North",
    type: "Recruitment",
    status: "Cancelled & retest",
    scale: "715 engineering posts scrapped; MMS leak confirmed",
    summary: "Question papers were transmitted from examination centres via MMS and answer codes were returned by SMS. Two vigilance inquiries verified the breach, leading to complete cancellation of 715 posts.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2012-vyapam-transport",
    date: "2012-08-12",
    exam: "MP Transport Constable Recruitment 2012",
    body: "MP Professional Examination Board (Vyapam)",
    state: "Madhya Pradesh",
    region: "West",
    type: "Defence & police",
    status: "Arrests & FIR",
    scale: "Former Cabinet Minister named in CBI FIR",
    summary: "The CBI named former minister Laxmikant Sharma, his personal staff, and Vyapam controllers in criminal conspiracy charges for rigging score sheets in the transport constable recruitment exam.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2012-tnpsc",
    date: "2012-08-12",
    exam: "TNPSC Group-II (Subordinate Services) 2012",
    body: "Tamil Nadu Public Service Commission",
    state: "Tamil Nadu",
    region: "South",
    type: "Recruitment",
    status: "Arrests & FIR",
    scale: "Question paper leaked via email on exam morning",
    summary: "The Group-II question paper was intercepted via email on the morning of the exam and circulated in Namakkal and Dharmapuri districts. CB-CID arrested government officials and middlemen.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2012-vyapam-constable",
    date: "2012-09-30",
    exam: "Vyapam Police Constable Recruitment 2012",
    body: "MP Professional Examination Board (Vyapam)",
    state: "Madhya Pradesh",
    region: "West",
    type: "Defence & police",
    status: "Convictions",
    scale: "11 individuals sentenced to 7 years rigorous imprisonment",
    summary: "Candidates arranged professional proxy impersonators to take physical and written tests. In May 2024, a special CBI court sentenced 11 convicts to seven years of rigorous imprisonment.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2012-food-inspector",
    date: "2012-10-07",
    exam: "MP Food Inspector Selection Test 2012",
    body: "MP Professional Examination Board (Vyapam)",
    state: "Madhya Pradesh",
    region: "West",
    type: "Recruitment",
    status: "Arrests & FIR",
    scale: "38 individuals booked by CBI",
    summary: "The CBI registered criminal cases against former Vyapam exam controller Pankaj Trivedi and 37 others for manipulating answer evaluations to appoint ineligible candidates.",
    sources: [WIKI_LIST],
  },

  /* ---------------- 2013 ---------------- */
  {
    id: "e2013-ssc-cgl",
    date: "2013-04-21",
    exam: "SSC Combined Graduate Level 2013",
    body: "Staff Selection Commission",
    state: "All India",
    region: "All-India",
    type: "Recruitment",
    status: "Cancelled & retest",
    scale: "14 arrests including police personnel; CAT ordered retest",
    summary: "Tier-I and Tier-II papers for inspector posts were leaked via digital storage drives and mobile phones. The Central Administrative Tribunal scrapped the examination and ordered a fresh test.",
    detail: "The 2013 Combined Graduate Level examination faced unprecedented malpractice across several northern zones when question sets were smuggled out of custodial test centres and distributed digitally.\n\nDelhi Police arrested 14 individuals, including serving police officers and coaching centre administrators who were managing electronic solver rooms.\n\nThe Central Administrative Tribunal (CAT) ruled that the integrity of the recruitment had been irreparably compromised, ordering the SSC to scrap the merit list and conduct nationwide re-evaluations.",
    keyFacts: [
      { k: "Scope", v: "Recruitment for Central Excise, Income Tax, and CBI Sub-Inspectors" },
      { k: "Intervention", v: "Central Administrative Tribunal (CAT) ordered cancellation" },
      { k: "Arrests", v: "14 individuals including serving law enforcement personnel" }
    ],
    sources: [WIKI_LIST],
  },
  {
    id: "e2013-vyapam-pmt",
    date: "2013-07-07",
    exam: "MP Pre-Medical Test 2013 (Vyapam)",
    body: "MP Professional Examination Board (Vyapam)",
    state: "Madhya Pradesh",
    region: "West",
    type: "Medical entrance",
    status: "Convictions",
    scale: "Engineered seating charts for solvers; 5 convicted in 2023",
    summary: "Seating arrangements and roll numbers were manipulated inside the board's mainframe system to place medical students directly next to paying clients. CBI courts convicted five accused in May 2023.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2013-vyapam-constable",
    date: "2013-09-15",
    exam: "Vyapam Police Constable Recruitment 2013",
    body: "MP Professional Examination Board (Vyapam)",
    state: "Madhya Pradesh",
    region: "West",
    type: "Defence & police",
    status: "Convictions",
    scale: "31 individuals convicted (2019) with up to 10-year sentences",
    summary: "A special court convicted 31 accused, including 12 proxy imposters, handing down sentences up to 10 years for forged identity cards and mass impersonation in police recruitment.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2013-ras",
    date: "2013-10-26",
    exam: "RAS Preliminary Examination 2013",
    body: "Rajasthan Public Service Commission",
    state: "Rajasthan",
    region: "North",
    type: "Civil services",
    status: "Cancelled & retest",
    scale: "~20 of top 50 rankers linked to leaked master paper",
    summary: "Rajasthan SOG discovered that nearly 20 of the top 50 selected candidates had obtained the leaked paper through an insider syndicate. RPSC cancelled the preliminary exam.",
    sources: [WIKI_LIST],
  },

  /* ---------------- 2014 ---------------- */
  {
    id: "e2014-apsc",
    date: "2014-05-04",
    exam: "APSC Combined Competitive (Cash-for-Jobs) 2013–14",
    body: "Assam Public Service Commission",
    state: "Assam",
    region: "Northeast",
    type: "Civil services",
    status: "Convictions",
    scale: "34 convicted including former APSC Chairman Rakesh Paul",
    summary: "Candidates paid massive cash bribes for civil service appointments. In July 2024, a special court in Gauhati convicted former APSC Chairman Rakesh Paul and 33 others in the landmark scam.",
    detail: "The Assam Public Service Commission 'Cash-for-Jobs' scandal exposed widespread institutionalized corruption in the state's highest administrative selection process.\n\nCandidates paid bribes ranging from ₹15 lakh to ₹50 lakh to have their answer scripts replaced with newly forged sheets containing correct answers written in private rooms after the official exam had concluded.\n\nIn July 2024, a Special Gauhati Court convicted 34 people, including former APSC Chairman Rakesh Paul and several state civil service officers who were dismissed from their posts.",
    keyFacts: [
      { k: "Key Accused", v: "Former APSC Chairman Rakesh Paul" },
      { k: "Convictions", v: "34 individuals convicted in July 2024" },
      { k: "Modus Operandi", v: "Post-exam replacement of original answer scripts with forged sheets" }
    ],
    sources: [WIKI_LIST],
  },
  {
    id: "e2014-ayurvedic",
    date: "2014-05-18",
    exam: "MPPSC Ayurvedic Medical Officers 2014",
    body: "MP Public Service Commission",
    state: "Madhya Pradesh",
    region: "West",
    type: "Recruitment",
    status: "Cancelled & retest",
    scale: "722 posts; interstate leak syndicate unmasked",
    summary: "MPPSC cancelled the recruitment examination after an STF probe confirmed that question papers had been leaked by an interstate gang prior to the test.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2014-upcpmt",
    date: "2014-06-22",
    exam: "UP Combined Pre-Medical Test 2014",
    body: "King George's Medical University, Lucknow",
    state: "Uttar Pradesh",
    region: "North",
    type: "Medical entrance",
    status: "Cancelled & retest",
    scale: "1 lakh+ candidates; bank vault paper boxes found tampered",
    summary: "Metal question paper boxes stored inside a Ghaziabad bank vault were found tampered with broken seals on the morning of the exam, forcing immediate statewide cancellation.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2014-dsssb-headclerk",
    date: "2014-06-29",
    exam: "DSSSB Head Clerk (DASS Grade-II) 2014",
    body: "Delhi Subordinate Services Selection Board",
    state: "Delhi",
    region: "North",
    type: "Recruitment",
    status: "Cancelled & retest",
    scale: "Supreme Court upheld total cancellation in 2021",
    summary: "Following extensive complaints of leaks and mass impersonation, the Delhi administration cancelled the recruitment. The Supreme Court upheld the cancellation in 2021 to protect public trust.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2014-wbtet",
    date: "2014-10-11",
    exam: "West Bengal Primary TET 2014",
    body: "WB Board of Primary Education",
    state: "West Bengal",
    region: "East",
    type: "Teacher eligibility",
    status: "Probe ordered",
    scale: "CBI / ED ongoing investigation into massive bribe nexus",
    summary: "Rampant irregularities, unverified appointments, and illegal score alterations plagued the 2014 primary teacher eligibility cycle, prompting High Court-monitored CBI and ED investigations.",
    sources: [WIKI_LIST],
  },

  /* ---------------- 2015 ---------------- */
  {
    id: "e2015-chandigarh",
    date: "2015-02-14",
    exam: "Chandigarh JBT & TGT Teacher Recruitment 2015",
    body: "Chandigarh Education Department",
    state: "Chandigarh",
    region: "North",
    type: "Teacher eligibility",
    status: "Convictions",
    scale: "1,150 posts; 42 appointed teachers terminated",
    summary: "Papers were leaked from a printing press in Delhi. A 1,000-page chargesheet was filed against kingpin 'Guruji' and 42 recruited teachers were subsequently dismissed from service.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2015-uppcs",
    date: "2015-03-29",
    exam: "UPPCS Preliminary Examination 2015",
    body: "UP Public Service Commission",
    state: "Uttar Pradesh",
    region: "North",
    type: "Civil services",
    status: "Cancelled & retest",
    scale: "Circulated on WhatsApp 1 hour before exam commencement",
    summary: "Paper-I was photographed at an exam centre in Lucknow and circulated on WhatsApp. The Chief Minister ordered immediate cancellation of the first paper and a fresh retest.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2015-aipmt",
    date: "2015-05-03",
    exam: "AIPMT 2015",
    body: "Central Board of Secondary Education",
    state: "All India",
    region: "All-India",
    type: "Medical entrance",
    status: "Cancelled & retest",
    scale: "Supreme Court ordered national retest for 6.3 lakh students",
    summary: "Haryana Police exposed an organized syndicate using micro-Bluetooth earpieces and tailored SIM jackets. The Supreme Court cancelled the exam and ordered a nationwide retest.",
    detail: "During the All India Pre-Medical Test in May 2015, Haryana Police in Rohtak intercepted an interstate network transmitting solved answer keys to candidates wearing custom-tailored innerwear stitched with micro-SIM transmitters and button earpieces.\n\nWhile CBSE argued that only a minuscule fraction of students had used the device, the Supreme Court of India ruled that the systemic sanctity of the national test had been compromised.\n\nIn a landmark ruling, the Supreme Court directed CBSE to scrap the entire examination and conduct a nationwide re-examination on July 25, 2015 for over 6.3 lakh candidates.",
    keyFacts: [
      { k: "Supreme Court Ruling", v: "Ordered total national retest (July 25, 2015)" },
      { k: "Technology Used", v: "Micro-SIM stitched innerwear and customized Bluetooth receivers" },
      { k: "Candidates Affected", v: "630,000 medical aspirants nationwide" }
    ],
    sources: [WIKI_LIST],
  },
  {
    id: "e2015-kvs",
    date: "2015-10-04",
    exam: "KVS Primary Teacher Recruitment 2015",
    body: "Kendriya Vidyalaya Sangathan",
    state: "All India",
    region: "All-India",
    type: "Teacher eligibility",
    status: "Cancelled & retest",
    scale: "13 arrests in Rewari; cancelled on exam day",
    summary: "KVS cancelled the written examination on the same day after electronic copies of the question paper were intercepted on WhatsApp, leading to 13 arrests in Rewari.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2015-punjab-lg",
    date: "2015-11-08",
    exam: "Punjab Local Government JE / SDE Recruitment 2015",
    body: "Department of Local Government, Punjab",
    state: "Punjab",
    region: "North",
    type: "Recruitment",
    status: "Arrests & FIR",
    scale: "600+ posts; papers sold for ₹10–40 lakh each",
    summary: "Question papers leaked from a Delhi printing facility were sold by an interstate syndicate for ₹10–40 lakh per candidate. State vigilance nullified the recruitment and arrested over 30 individuals.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2015-htet",
    date: "2015-11-14",
    exam: "HTET Level-3 (Haryana TET) 2015",
    body: "Board of School Education Haryana",
    state: "Haryana",
    region: "North",
    type: "Teacher eligibility",
    status: "Cancelled & retest",
    scale: "Level-3 test cancelled; solver gang dismantled in Jind",
    summary: "The Level-3 teacher eligibility test was cancelled following an advance leak and widespread digital circulation. Police dismantled an active solver syndicate in Jind.",
    sources: [WIKI_LIST],
  },

  /* ---------------- 2016 ---------------- */
  {
    id: "e2016-uksssc-vpdo",
    date: "2016-03-06",
    exam: "UKSSSC Village Panchayat Development Officer 2016",
    body: "Uttarakhand SS Selection Commission",
    state: "Uttarakhand",
    region: "North",
    type: "Recruitment",
    status: "Arrests & FIR",
    scale: "Former UKSSSC Chairman and Exam Controller arrested",
    summary: "Uttarakhand STF arrested former UKSSSC Chairman R.B.S. Rawat and key commission controllers after forensic probes verified question leaks and post-exam OMR manipulation.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2016-ssc-cpo",
    date: "2016-03-20",
    exam: "SSC CPO Sub-Inspector Paper-I 2016",
    body: "Staff Selection Commission",
    state: "All India",
    region: "All-India",
    type: "Defence & police",
    status: "Cancelled & retest",
    scale: "Circulated on Facebook 5 hours before exam",
    summary: "The question paper was posted publicly on a coaching operator's Facebook page five hours ahead of the scheduled test time, forcing SSC to cancel Paper-I and reconduct it.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2016-neet-phase2",
    date: "2016-05-01",
    exam: "NEET-UG 2016 (Phase II)",
    body: "Central Board of Secondary Education",
    state: "All India",
    region: "All-India",
    type: "Medical entrance",
    status: "Alleged only",
    scale: "Interstate touts arrested in Uttarakhand; no national retest",
    summary: "Allegations of question paper leakage surfaced in Uttarakhand, resulting in arrests of coaching operators. CBSE maintained that the main paper remained secure, avoiding a national retest.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2016-tseamcet",
    date: "2016-07-09",
    exam: "TS EAMCET-II (Medical) 2016",
    body: "JNTU Hyderabad",
    state: "Telangana",
    region: "South",
    type: "Medical entrance",
    status: "Cancelled & retest",
    scale: "20+ brokers arrested; leak sourced to printing press in Delhi",
    summary: "CID confirmed question papers were stolen directly from a printing press in Delhi. The Telangana government cancelled the exam, arrested over 20 brokers, and held a fresh test.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2016-manipur",
    date: "2016-09-04",
    exam: "Manipur Civil Services (Main) 2016",
    body: "Manipur Public Service Commission",
    state: "Manipur",
    region: "Northeast",
    type: "Civil services",
    status: "Results nullified",
    scale: "82 civil service appointments quashed by High Court",
    summary: "A judicial inquiry identified missing examiner signatures and arbitrary score adjustments. The Manipur High Court quashed all 82 appointments, upheld by the Supreme Court.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2016-wbslst",
    date: "2016-11-27",
    exam: "WB SLST Teacher & Group C/D 2016",
    body: "WB School Service Commission",
    state: "West Bengal",
    region: "East",
    type: "Recruitment",
    status: "Results nullified",
    scale: "25,753 appointments declared null and void by Calcutta HC",
    summary: "In a monumental ruling, the Calcutta High Court declared all 25,753 appointments under the 2016 SLST cycle null and void, citing systemic manipulation of OMR answer sheets and rank lists.",
    detail: "The West Bengal School Service Commission (SSC) 2016 recruitment was marked by unprecedented administrative fraud, where unranked and failing candidates were granted teacher and non-teaching staff appointments in exchange for crores in bribes.\n\nCBI and ED investigations revealed thousands of blank OMR sheets that were retroactively assigned high marks inside SSC servers.\n\nIn April 2024, a Special Division Bench of the Calcutta High Court cancelled all 25,753 appointments made through the 2016 recruitment drive, ordering beneficiaries to refund salaries with interest.",
    keyFacts: [
      { k: "Scale", v: "25,753 teaching and non-teaching posts nullified" },
      { k: "High-Profile Arrests", v: "Former Education Minister Partha Chatterjee and top SSC officials" },
      { k: "Judicial Order", v: "Calcutta High Court Division Bench cancelled recruitment (April 2024)" }
    ],
    sources: [WIKI_LIST],
  },
  {
    id: "e2016-uppsc-roaro",
    date: "2016-11-27",
    exam: "UPPSC RO / ARO Prelims 2016",
    body: "UP Public Service Commission",
    state: "Uttar Pradesh",
    region: "North",
    type: "Civil services",
    status: "Cancelled & retest",
    scale: "Circulation on WhatsApp confirmed; retest ordered",
    summary: "UPPSC cancelled the Review Officer / Assistant Review Officer preliminary exam following conclusive proof that question papers were circulating on WhatsApp prior to the morning session.",
    sources: [WIKI_LIST],
  },

  /* ---------------- 2017 ---------------- */
  {
    id: "e2017-bssc",
    date: "2017-02-05",
    exam: "BSSC Inter-Level (Clerical) 2017",
    body: "Bihar Staff Selection Commission",
    state: "Bihar",
    region: "East",
    type: "Recruitment",
    status: "Arrests & FIR",
    scale: "17.5 lakh applicants; BSSC Chairman (senior IAS) arrested",
    summary: "Question papers and answer keys were leaked on WhatsApp. A Special Investigation Team arrested BSSC Chairman Sudhir Kumar (senior IAS officer) and Secretary Parmeshwar Ram.",
    detail: "Over 17.5 lakh youth applied for 13,000 clerical positions in Bihar's largest recruitment cycle. On the morning of Phase-I testing, question papers and solved answer keys spread rapidly across social media.\n\nA state SIT uncovered that the leak originated directly from the commission's highest echelons.\n\nPolice arrested sitting BSSC Chairman Sudhir Kumar, an active Senior IAS officer, alongside the commission's secretary and printing press executives, leading to the cancellation of the multi-phase exam.",
    keyFacts: [
      { k: "Total Applicants", v: "1.75 million candidates" },
      { k: "Key Accused", v: "Sitting BSSC Chairman Sudhir Kumar (IAS) and Secretary Parmeshwar Ram" },
      { k: "Scale", v: "Over 30 individuals arrested across government and private sectors" }
    ],
    sources: [WIKI_LIST],
  },
  {
    id: "e2017-army-cee",
    date: "2017-02-26",
    exam: "Indian Army Common Entrance Exam 2017",
    body: "Indian Army",
    state: "Maharashtra",
    region: "West",
    type: "Defence & police",
    status: "Cancelled & retest",
    scale: "Nationwide CEE cancelled; 18 arrests across Maharashtra and Goa",
    summary: "Thane Police Crime Branch and Military Intelligence intercepted an interstate racket selling leaked questions to 350+ candidates in lodges. The Army cancelled the exam across multiple zones.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2017-ssc-mts",
    date: "2017-04-30",
    exam: "SSC Multi-Tasking Staff 2017",
    body: "Staff Selection Commission",
    state: "All India",
    region: "All-India",
    type: "Recruitment",
    status: "Cancelled & retest",
    scale: "Millions of candidates; offline pen-paper format permanently abolished",
    summary: "Following widespread online leaks of question papers and answer sheets in Delhi and Patna, SSC cancelled the entire examination cycle and permanently shifted MTS to computer-based testing.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2017-neet",
    date: "2017-05-07",
    exam: "NEET-UG 2017",
    body: "Central Board of Secondary Education",
    state: "All India",
    region: "All-India",
    type: "Medical entrance",
    status: "Arrests & FIR",
    scale: "Solver syndicates intercepted in Patna, Jaipur, and Goa",
    summary: "Police intercepted commercial solver gangs in Patna and Jaipur operating with electronic transmitters and pre-solved answer keys across multiple examination centres.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2017-hcs",
    date: "2017-07-16",
    exam: "HCS (Judicial Branch) Prelims 2017",
    body: "Punjab & Haryana High Court",
    state: "Haryana",
    region: "North",
    type: "Professional",
    status: "Convictions",
    scale: "109 judicial posts; High Court Registrar (Recruitment) convicted",
    summary: "A High Court committee confirmed that the judicial preliminary paper was leaked by Registrar (Recruitment) Balwinder Kumar Sharma for ₹1.5 crore. Sharma was arrested and subsequently convicted.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2017-upsi",
    date: "2017-07-24",
    exam: "UP Police Sub-Inspector Online Test 2017",
    body: "UP Police Recruitment & Promotion Board",
    state: "Uttar Pradesh",
    region: "North",
    type: "Defence & police",
    status: "Cancelled & retest",
    scale: "Online exam portal hacked; month-long recruitment cancelled",
    summary: "The recruitment board cancelled the month-long online computer-based exam after UP STF uncovered cyber intrusions and remote-desktop compromises across private testing lab servers.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2017-tnpsc-iia",
    date: "2017-08-06",
    exam: "TNPSC Group II-A Services 2017",
    body: "Tamil Nadu Public Service Commission",
    state: "Tamil Nadu",
    region: "South",
    type: "Recruitment",
    status: "Arrests & FIR",
    scale: "Disappearing-ink pens used for post-exam OMR tampering",
    summary: "Candidates used special pens with vanishing ink so accomplices could shade correct answers while answer sheets were in transit to Chennai. Over 40 candidates, agents, and staff were arrested.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2017-trb",
    date: "2017-09-16",
    exam: "TRB Polytechnic Lecturer 2017",
    body: "Teachers Recruitment Board, TN",
    state: "Tamil Nadu",
    region: "South",
    type: "Recruitment",
    status: "Results nullified",
    scale: "~200 OMR sheets tampered inside commission strongroom",
    summary: "Marks for nearly 200 candidates were fraudulently inflated directly inside TRB headquarters. The entire selection list was quashed following CB-CID and ED investigations.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2017-dsssb-prt",
    date: "2017-10-29",
    exam: "DSSSB Primary Teacher (PRT) 2017",
    body: "Delhi Subordinate Services Selection Board",
    state: "Delhi",
    region: "North",
    type: "Teacher eligibility",
    status: "Cancelled & retest",
    scale: "4,366 posts; 1 lakh+ candidates; LG ordered cancellation",
    summary: "The Lt. Governor of Delhi cancelled the recruitment of 4,366 teachers after Crime Branch confirmed question papers were leaked on WhatsApp and solved electronically by an organized ring.",
    sources: [WIKI_LIST],
  },

  /* ---------------- 2018 ---------------- */
  {
    id: "e2018-ssc-cgl",
    date: "2018-02-21",
    exam: "SSC CGL 2017 Tier-II",
    body: "Staff Selection Commission",
    state: "All India",
    region: "All-India",
    type: "Recruitment",
    status: "Arrests & FIR",
    scale: "Massive youth protests at CGO Complex; 17 booked by CBI",
    summary: "Screenshots of the computer-based exam and answer keys leaked before test completion. Tens of thousands of students camped at the CGO Complex in Delhi, prompting a CBI inquiry that booked 17 accused.",
    detail: "In February 2018, screenshots of active computer screens running the Tier-II Quantitative Aptitude paper appeared on social media while candidates were supposedly sitting inside secure test centres.\n\nThe breach triggered the historic SSC CGL Protests, with tens of thousands of aspirants staging an indefinite sit-in outside the SSC headquarters at CGO Complex, New Delhi.\n\nThe Supreme Court took cognizance of the protests, and the CBI booked 17 individuals, including employees of private testing vendor Sify Technologies, for remote screen-sharing fraud.",
    keyFacts: [
      { k: "Public Action", v: "Weeks-long sit-in protest by thousands of aspirants at CGO Complex, Delhi" },
      { k: "CBI Investigation", v: "17 individuals booked including employees of vendor Sify Technologies" },
      { k: "Modus Operandi", v: "Remote-access desktop sharing via TeamViewer/AnyDesk inside exam labs" }
    ],
    sources: [WIKI_LIST],
  },
  {
    id: "e2018-rj-police",
    date: "2018-03-07",
    exam: "Rajasthan Police Constable 2018",
    body: "Rajasthan Police Recruitment Board",
    state: "Rajasthan",
    region: "North",
    type: "Defence & police",
    status: "Cancelled & retest",
    scale: "Online exam cancelled after remote-access cyber hack detected",
    summary: "An interstate cyber gang utilized remote-access software to solve online exam papers from external hideouts, compelling authorities to cancel the computer-based exam.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2018-uppcl",
    date: "2018-03-31",
    exam: "UPPCL JE / Technician 2018",
    body: "UP Power Corporation",
    state: "Uttar Pradesh",
    region: "North",
    type: "Recruitment",
    status: "Cancelled & retest",
    scale: "Testing agency blacklisted; multiple exams nullified",
    summary: "UP STF detected mass online hacking and answer manipulation, prompting the state power corporation to nullify recruitment exams and blacklist the private testing vendor.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2018-kerala-psc",
    date: "2018-05-26",
    exam: "Kerala PSC University Assistant & Police Officer 2018",
    body: "Kerala Public Service Commission",
    state: "Kerala",
    region: "South",
    type: "Recruitment",
    status: "Results nullified",
    scale: "Smartwatch communication ring; top rankers debarred for life",
    summary: "Top-ranking candidates used smartwatches to transmit question images and receive answers via SMS from police accomplices. Kerala PSC permanently debarred the accused.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2018-up-constable",
    date: "2018-06-18",
    exam: "UP Police Constable 2018 (Shift 2)",
    body: "UP Police Recruitment & Promotion Board",
    state: "Uttar Pradesh",
    region: "North",
    type: "Defence & police",
    status: "Cancelled & retest",
    scale: "56 exam centres cancelled; wrong question sets distributed",
    summary: "The recruitment board cancelled second-shift exams across 56 centres after compromised question sets were mistakenly distributed in place of the scheduled series.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2018-uppsc-lt",
    date: "2018-06-29",
    exam: "UPPSC LT Grade Assistant Teacher 2018",
    body: "UP Public Service Commission",
    state: "Uttar Pradesh",
    region: "North",
    type: "Teacher eligibility",
    status: "Arrests & FIR",
    scale: "Exam Controller Anju Katiyar arrested by UP STF",
    summary: "UP STF arrested UPPSC Examination Controller Anju Katiyar and a Kolkata printing press proprietor after Hindi and Social Science question papers were leaked for ₹15 lakh per candidate.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2018-gujarat-tat",
    date: "2018-07-29",
    exam: "Gujarat Teacher Aptitude Test 2018",
    body: "State Examination Board, Gujarat",
    state: "Gujarat",
    region: "West",
    type: "Teacher eligibility",
    status: "Cancelled & retest",
    scale: "~1.47 lakh candidates affected across Gujarat",
    summary: "The Teacher Aptitude Test paper leaked on social media hours ahead of the scheduled examination, forcing the State Examination Board to cancel the test and order a re-examination.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2018-upsssc-nalkoop",
    date: "2018-09-02",
    exam: "UPSSSC Tubewell Operator 2018",
    body: "UP Subordinate Services Selection Commission",
    state: "Uttar Pradesh",
    region: "North",
    type: "Recruitment",
    status: "Cancelled & retest",
    scale: "Hindi paper viral on WhatsApp; 11 arrested in Meerut",
    summary: "The Hindi question paper leaked on social media the night before testing. UP STF arrested 11 syndicate members in Meerut, recovering ₹15 lakh in cash and solved question sets.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2018-up-btc",
    date: "2018-10-08",
    exam: "UP BTC 4th Semester Exam 2018",
    body: "Examination Regulatory Authority, UP",
    state: "Uttar Pradesh",
    region: "North",
    type: "Teacher eligibility",
    status: "Cancelled & retest",
    scale: "Statewide cancellation after WhatsApp leaks in Prayagraj",
    summary: "Question papers were leaked from examination centres in Kaushambi and Prayagraj via WhatsApp. The state government cancelled the exam and arrested coaching centre operators.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2018-gujarat-lrd",
    date: "2018-12-02",
    exam: "Gujarat Lokrakshak Dal Constable 2018",
    body: "Lokrakshak Recruitment Board",
    state: "Gujarat",
    region: "West",
    type: "Defence & police",
    status: "Cancelled & retest",
    scale: "8.75 lakh candidates; 2,440 centres; cancelled hours before",
    summary: "The written test for 8.75 lakh candidates was called off hours before commencement when answer keys matching the master question paper were intercepted by state police.",
    detail: "Over 8.75 lakh candidates had arrived at 2,440 examination centres across Gujarat on December 2, 2018, when authorities abruptly announced the total cancellation of the Lokrakshak Dal recruitment.\n\nState ATS and Crime Branch units intercepted hand-copied answer keys that matched the confidential question paper with 100% accuracy.\n\nThe leak was traced to a printing press in Delhi via a multi-state broker network. Over 30 individuals, including a police sub-inspector and political party office-bearers, were arrested, and a smooth re-test was conducted on January 6, 2019.",
    keyFacts: [
      { k: "Candidate Footprint", v: "875,000 candidates across 2,440 centres" },
      { k: "Point of Compromise", v: "Printing facility in Delhi via interstate broker network" },
      { k: "Retest Delivery", v: "Successfully re-administered on January 6, 2019" }
    ],
    sources: [WIKI_LIST],
  },
  {
    id: "e2018-upsssc-vdo",
    date: "2018-12-22",
    exam: "UPSSSC Village Development Officer 2018",
    body: "UP Subordinate Services Selection Commission",
    state: "Uttar Pradesh",
    region: "North",
    type: "Recruitment",
    status: "Cancelled & retest",
    scale: "1,953 posts; mass OMR sheet tampering confirmed",
    summary: "An SIT probe established that OMR sheets of hundreds of selected candidates were forged inside strongrooms post-examination. The recruitment of 1,953 VDO positions was cancelled.",
    sources: [WIKI_LIST],
  },

  /* ---------------- 2019 ---------------- */
  {
    id: "e2019-otet",
    date: "2019-01-16",
    exam: "Odisha Teacher Eligibility Test 2018/19",
    body: "Board of Secondary Education, Odisha",
    state: "Odisha",
    region: "East",
    type: "Teacher eligibility",
    status: "Cancelled & retest",
    scale: "1.11 lakh candidates; 250 examination centres",
    summary: "Question papers for the first shift went viral on social media during the exam. The BSE President cancelled the examination across all 250 centres and transferred the case to the Crime Branch.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2019-rrb-je",
    date: "2019-08-28",
    exam: "RRB Junior Engineer Stage-2 CBT 2019",
    body: "Railway Recruitment Control Board",
    state: "Maharashtra",
    region: "West",
    type: "Recruitment",
    status: "Arrests & FIR",
    scale: "Remote-access terminal intrusion at Thane test centre",
    summary: "Thane Police filed an FIR after discovering that computer terminals inside an authorized testing lab were being operated remotely by solvers outside the facility.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2019-tnpsc-g4",
    date: "2019-09-01",
    exam: "TNPSC Group-IV 2019",
    body: "Tamil Nadu Public Service Commission",
    state: "Tamil Nadu",
    region: "South",
    type: "Recruitment",
    status: "Arrests & FIR",
    scale: "118 arrests; 99 top rankers used vanishing-ink pens",
    summary: "An investigation revealed that 99 of the top 100 rankers took their exams in Rameswaram using disappearing-ink pens, allowing accomplices to re-shade OMRs during transit to Chennai.",
    detail: "The 2019 TNPSC Group-IV examination uncovered an ingenious fraud network operating in Rameswaram and Keelakarai examination centres in Tamil Nadu.\n\nCandidates were instructed by brokers to write their examinations with special pens whose ink evaporated within hours. Accomplices in transit vehicles subsequently filled in correct answers on the blank OMR sheets before delivery to the TNPSC vault in Chennai.\n\nCB-CID arrested 118 individuals, including commission staff, revenue officials, and intermediaries. In 2021, the Madras High Court ordered a CBI inquiry into deep-rooted systemic links.",
    keyFacts: [
      { k: "Investigation Scale", v: "118 arrests including government staff and intermediaries" },
      { k: "Modus Operandi", v: "Vanishing-ink pens with in-transit OMR replacement" },
      { k: "Anomalous Clustering", v: "99 of the top 100 rankers originated from two specific centres" }
    ],
    sources: [WIKI_LIST],
  },
  {
    id: "e2019-gsssb",
    date: "2019-11-17",
    exam: "GSSSB Bin Sachivalay Clerk 2019",
    body: "Gujarat Subordinate Services Selection Board",
    state: "Gujarat",
    region: "West",
    type: "Recruitment",
    status: "Cancelled & retest",
    scale: "6 lakh candidates; 3,910 posts; mass student mobilization",
    summary: "Widespread student protests in Gandhinagar forced the state government to constitute an SIT, which confirmed question leaks, mobile phone usage in centres, and CCTV tampering.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2019-hssc-iti",
    date: "2019-12-05",
    exam: "HSSC ITI Instructor 2019",
    body: "Haryana Staff Selection Commission",
    state: "Haryana",
    region: "North",
    type: "Recruitment",
    status: "Arrests & FIR",
    scale: "Computer lab manager arrested while operating solver ring",
    summary: "Chandigarh Police raided an authorized private online testing lab, catching the lab manager and technical assistants transmitting live questions and feeding answers to 11 candidates.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2019-librarian",
    date: "2019-12-29",
    exam: "Rajasthan Librarian Grade-III 2019",
    body: "Rajasthan Staff Selection Board (RSMSSB)",
    state: "Rajasthan",
    region: "North",
    type: "Recruitment",
    status: "Cancelled & retest",
    scale: "Question paper leaked on WhatsApp 2 hours prior",
    summary: "The question paper and complete answer key were circulated on WhatsApp groups two hours before the test. RSMSSB cancelled the exam and police arrested six key conspirators.",
    sources: [WIKI_LIST],
  },

  /* ---------------- 2020 ---------------- */
  {
    id: "e2020-mahatet",
    date: "2020-01-16",
    exam: "MAHA-TET 2019–20",
    body: "Maharashtra State Council of Examinations",
    state: "Maharashtra",
    region: "West",
    type: "Teacher eligibility",
    status: "Convictions",
    scale: "₹2.5 crore cash and gold seized; 7,800 candidates blacklisted",
    summary: "Pune Cyber Police uncovered massive back-end score alterations. Two former MSCE Commissioners and the director of the private testing agency were arrested, leading to 7,800 candidates being barred.",
    detail: "The Maharashtra Teacher Eligibility Test (MAHA-TET) scam exposed an organized extortion racket inside the state's examination regulatory bodies.\n\nPune Cyber Police discovered that private agency GA Software directors and MSCE commissioners were directly modifying candidate scores in the official database for ₹1–2 lakh per candidate.\n\nPolice seized over ₹2.5 crore in cash, gold ornaments, and fixed-deposit certificates from the residences of officials, resulting in the lifetime debarment of 7,800 candidates who paid bribes.",
    keyFacts: [
      { k: "Seizures", v: "₹2.5 crore cash, gold bars, and property deeds" },
      { k: "High-Profile Arrests", v: "Two former MSCE Commissioners and testing vendor director" },
      { k: "Sanctions", v: "7,800 fraudulent candidates permanently debarred" }
    ],
    sources: [WIKI_LIST],
  },
  {
    id: "e2020-bihar-stet",
    date: "2020-01-28",
    exam: "Bihar STET 2019",
    body: "Bihar School Examination Board",
    state: "Bihar",
    region: "East",
    type: "Teacher eligibility",
    status: "Cancelled & retest",
    scale: "317 centres cancelled; switched to online CBT format",
    summary: "A four-member vigilance inquiry confirmed question leaks and electronic circulation in multiple districts. BSEB cancelled the examination across all 317 centres.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2020-apssb",
    date: "2020-02-02",
    exam: "APSSB LDC / Junior Secretariat Assistant 2020",
    body: "Arunachal Pradesh Staff Selection Board",
    state: "Arunachal Pradesh",
    region: "Northeast",
    type: "Recruitment",
    status: "Arrests & FIR",
    scale: "Blank OMRs shortlisted; APSSB Undersecretary arrested",
    summary: "Candidates who submitted completely blank OMR sheets were discovered in the official merit shortlist. The State Special Investigation Cell arrested the APSSB Undersecretary and touts.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2020-assam-si",
    date: "2020-09-20",
    exam: "Assam Police Sub-Inspector (UB) 2020",
    body: "State Level Police Recruitment Board",
    state: "Assam",
    region: "Northeast",
    type: "Defence & police",
    status: "Cancelled & retest",
    scale: "66,000 candidates; retired DIG and senior SP arrested",
    summary: "The question paper went viral minutes into the exam. SLPRB Chairman resigned, the exam for 66,000 candidates was cancelled, and CID arrested over 40 accused including a retired DIG.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2020-punjab-dental",
    date: "2020-10-11",
    exam: "Medical Officer (Dental) Recruitment 2020",
    body: "Baba Farid University of Health Sciences",
    state: "Punjab",
    region: "North",
    type: "Recruitment",
    status: "Cancelled & retest",
    scale: "1,957 candidates retested for 35 medical officer posts",
    summary: "The dental officer recruitment paper went viral on WhatsApp 80 minutes after testing began. BFUHS traced the leak to a single centre and conducted a fresh re-test.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2020-guvnl",
    date: "2020-12-01",
    exam: "Gujarat DISCOMs Vidyut Sahayak 2020",
    body: "Gujarat Urja Vikas Nigam",
    state: "Gujarat",
    region: "West",
    type: "Recruitment",
    status: "Arrests & FIR",
    scale: "Screen-splitter hardware and dual monitors used by solvers",
    summary: "Surat Crime Branch dismantled a high-tech rigging syndicate that used custom screen-splitter hardware and dual monitors to allow external solvers to answer CBT questions remotely.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2020-rsmssb-je",
    date: "2020-12-06",
    exam: "RSMSSB Junior Engineer (JEN) 2020",
    body: "Rajasthan Staff Selection Board",
    state: "Rajasthan",
    region: "North",
    type: "Recruitment",
    status: "Cancelled & retest",
    scale: "24 arrests; 2021 retest also compromised",
    summary: "The Civil Degree paper leaked from a government school centre in Jaipur. RSMSSB cancelled the exam; the 2021 re-test was also compromised by an engineering gang.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2020-appsc",
    date: "2020-12-14",
    exam: "APPSC Group-I Mains (2018 notification)",
    body: "Andhra Pradesh Public Service Commission",
    state: "Andhra Pradesh",
    region: "South",
    type: "Civil services",
    status: "Results nullified",
    scale: "95%+ evaluated scripts tampered with correction fluid",
    summary: "Forensic evaluation revealed manual mark alterations and extensive use of correction fluid across selected candidates' answer scripts. Andhra Pradesh High Court quashed the merit list.",
    sources: [WIKI_LIST],
  },

  /* ---------------- 2021 ---------------- */
  {
    id: "e2021-railway-gdce",
    date: "2021-01-03",
    exam: "Railway GDCE (RRC Mumbai) 2021",
    body: "Railway Recruitment Cell, Western Railway",
    state: "All India",
    region: "All-India",
    type: "Recruitment",
    status: "Arrests & FIR",
    scale: "10 railway officials and private testing vendor named",
    summary: "Candidates received solved answer sheets on WhatsApp prior to test entry. The CBI chargesheeted 15 individuals, including officials of private testing vendor Aptech and railway staff.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2021-hssc-gramsachiv",
    date: "2021-01-09",
    exam: "HSSC Gram Sachiv 2021",
    body: "Haryana Staff Selection Commission",
    state: "Haryana",
    region: "North",
    type: "Recruitment",
    status: "Cancelled & retest",
    scale: "697 posts; 18 arrests across multiple districts",
    summary: "The commission cancelled the recruitment of 697 village secretaries after state police intercepted WhatsApp answer keys transmitting to candidates inside test centres.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2021-itbp",
    date: "2021-01-10",
    exam: "ITBP Constable (Tradesmen) 2021",
    body: "Indo-Tibetan Border Police",
    state: "All India",
    region: "All-India",
    type: "Defence & police",
    status: "Arrests & FIR",
    scale: "46,174 candidates; private vendor executives arrested",
    summary: "The written question paper reached candidates on WhatsApp prior to commencement across 81 centres. Delhi Police arrested five accused, including private testing agency directors.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2021-kpsc-fda",
    date: "2021-01-24",
    exam: "KPSC First Division Assistant 2021",
    body: "Karnataka Public Service Commission",
    state: "Karnataka",
    region: "South",
    type: "Recruitment",
    status: "Arrests & FIR",
    scale: "12 arrests on the eve of the exam; ₹24 lakh cash seized",
    summary: "Bengaluru Central Crime Branch intercepted an active paper leak ring the night before the examination, recovering leaked question papers and ₹24 lakh cash. KPSC postponed the test.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2021-ctet",
    date: "2021-01-31",
    exam: "CTET January 2021",
    body: "Central Board of Secondary Education",
    state: "All India",
    region: "All-India",
    type: "Teacher eligibility",
    status: "Arrests & FIR",
    scale: "Coaching institute director and syndicate members arrested",
    summary: "Solved question papers were circulated on WhatsApp shortly before the examination. Uttar Pradesh Police arrested five individuals, including a prominent coaching institute director in Agra.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2021-reet",
    date: "2021-09-01",
    exam: "REET Level-2 (Rajasthan Teacher Eligibility) 2021",
    body: "Board of Secondary Education, Rajasthan",
    state: "Rajasthan",
    region: "North",
    type: "Teacher eligibility",
    status: "Cancelled & retest",
    scale: "16 lakh+ aspirants; paper stolen from Shiksha Sankul strongroom",
    summary: "The Level-2 paper was stolen from the state education strongroom in Jaipur and sold for ₹1.2 crore. The government cancelled Level-2, passed a stringent anti-leak law, and the ED launched a money-laundering probe.",
    detail: "The 2021 Rajasthan Eligibility Examination for Teachers (REET) was one of the largest competitive tests in Indian history, with over 16 lakh candidates appearing under massive security that included statewide mobile internet blackouts.\n\nDespite these restrictions, an employee deployed inside the high-security Shiksha Sankul strongroom in Jaipur opened sealed master packets two days prior, photographed the question sheets, and sold them to political touts for ₹1.2 crore.\n\nThe Rajasthan government cancelled the Level-2 exam affecting over 9 lakh candidates, dismissed the RBSE Chairman, and enacted the Rajasthan Public Examinations Act carrying up to 10 years imprisonment and ₹10 crore fines.",
    keyFacts: [
      { k: "Scale", v: "1.6 million registered candidates; statewide internet blackouts" },
      { k: "Breach Location", v: "Stolen directly from Jaipur Shiksha Sankul strongroom" },
      { k: "Legal Fallout", v: "Passage of Rajasthan anti-cheating law with ₹10 crore fines and ED attachments" }
    ],
    sources: [
      WIKI_LIST,
      { label: "The Hindu — ED arrests in REET case", url: "https://www.thehindu.com/news/national/rajasthan/ed-arrests-key-official-in-rajasthan-teachers-recruitment-exam-paper-leak-case/article68393466.ece" },
      { label: "Economic Times — REET 2021 leak ED arrest", url: "https://economictimes.indiatimes.com/news/india/rajasthan-ed-arrests-retd-professor-in-reet-2021-paper-leak-case/articleshow/111665809.cms" },
      { label: "Indian Express — Rajasthan testing times", url: "https://indianexpress.com/article/cities/jaipur/testing-times-rajasthan-govt-failure-to-plug-question-paper-leaks-8455665/" },
    ],
  },
  {
    id: "e2021-rj-si",
    date: "2021-09-01",
    exam: "Rajasthan Police Sub-Inspector Recruitment 2021",
    body: "Rajasthan Police Recruitment Board",
    state: "Rajasthan",
    region: "North",
    type: "Defence & police",
    status: "Arrests & FIR",
    scale: "Trainee sub-inspectors and RPSC members under active investigation",
    summary: "Bikaner and Jaipur police exposed an organized network that leaked question papers to dozens of candidates who subsequently secured selection and entered the police training academy.",
    sources: [
      WIKI_LIST,
      { label: "Indian Express — Testing times (Feb 2023)", url: "https://indianexpress.com/article/cities/jaipur/testing-times-rajasthan-govt-failure-to-plug-question-paper-leaks-8455665/" },
    ],
  },

  /* ---------------- 2022 ---------------- */
  {
    id: "e2022-bpsc-67",
    date: "2022-05-08",
    exam: "BPSC 67th Combined Prelims 2022",
    body: "Bihar Public Service Commission",
    state: "Bihar",
    region: "East",
    type: "Civil services",
    status: "Cancelled & retest",
    scale: "6 lakh candidates; cancelled within hours of test completion",
    summary: "Question paper sets were leaked on Telegram and circulated fifteen minutes prior to the examination. BPSC cancelled the exam the same evening, ordering a multi-agency criminal investigation.",
    detail: "Over 6 lakh aspirants appeared for the 67th Combined Preliminary Examination at 1,083 centres across Bihar on May 8, 2022.\n\nShortly before the 12:00 PM start, question papers were photographed inside an exam centre in Ara (Bhojpur) and circulated across Telegram channels.\n\nBPSC Chairman formed a three-member inquiry panel that verified the authenticity of the leaked papers within three hours, resulting in an unprecedented same-day cancellation and an Economic Offences Unit (EOU) probe that arrested several administrative officers.",
    keyFacts: [
      { k: "Candidate Footprint", v: "600,000 aspirants across 1,083 examination centres" },
      { k: "Speed of Action", v: "Cancelled the exact same day following immediate forensic match" },
      { k: "Arrests", v: "Block Development Officer (BDO) and centre administrators arrested" }
    ],
    sources: [
      WIKI_LIST,
      { label: "Times of India — BPSC 67th leak, probe ordered (May 2022)", url: "https://timesofindia.indiatimes.com/education/news/bpsc-67th-paper-leaked-before-exam-probe-ordered-by-bihar-public-service-commission/articleshow/91422914.cms" },
    ],
  },
  {
    id: "e2022-up-police-si",
    date: "2022-06-01",
    exam: "UP Police SI & Computer Operator recruitment",
    body: "UP Police Recruitment & Promotion Board",
    state: "Uttar Pradesh",
    region: "North",
    type: "Defence & police",
    status: "Cancelled & retest",
    scale: "Multi-day online testing cycle compromised by remote hacking",
    summary: "UP STF dismantled an interstate cyber syndicate that manipulated computer screens in testing centres across northern Uttar Pradesh, leading to widespread arrests and recruitment cancellations.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2022-tspscl",
    date: "2022-10-01",
    exam: "TSPSC recruitment exams (Telangana)",
    body: "Telangana State Public Service Commission",
    state: "Telangana",
    region: "South",
    type: "Recruitment",
    status: "Arrests & FIR",
    scale: "Confidential server databases hacked; multiple exams cancelled",
    summary: "Commission employees hacked internal confidential servers and extracted question papers for Group-I, Assistant Engineer, and Town Planning exams, selling them to prospective candidates.",
    detail: "The Telangana State Public Service Commission (TSPSC) faced a catastrophic breach of trust when an internal network administrator and a section officer used administrative credentials to access confidential question paper databases.\n\nMultiple examination sets—including the prestigious Group-I Preliminary Test and Assistant Engineer recruitment—were stolen, printed, and sold for ₹25–50 lakh per candidate.\n\nSpecial Investigation Team (SIT) and Enforcement Directorate arrested over 50 individuals, resulting in the cancellation of multiple exams and triggering massive student protests in Hyderabad.",
    keyFacts: [
      { k: "Vulnerability", v: "Insider credential theft from confidential commission database servers" },
      { k: "Exams Cancelled", v: "Group-I Prelims, Assistant Engineer, Town Planning Officer" },
      { k: "Prosecution", v: "Over 50 individuals arrested by SIT and Enforcement Directorate" }
    ],
    sources: [WIKI_LIST],
  },
  {
    id: "e2022-rj-cluster",
    date: "2022-12-01",
    exam: "Rajasthan recruitment exams (Patwari & 5 others under scanner)",
    body: "RSMSSB and others",
    state: "Rajasthan",
    region: "North",
    type: "Recruitment",
    status: "Arrests & FIR",
    scale: "6 major competitive examinations compromised by single syndicate",
    summary: "Rajasthan SOG intercepted a moving bus carrying 45 candidates memorizing leaked Teacher Grade-II papers, unraveling a syndicate that had compromised six separate recruitment drives.",
    sources: [
      { label: "India Today — 6 exams under radar (Dec 2022)", url: "https://www.indiatoday.in/india/story/rajasthan-paper-leak-cases-six-exams-held-2313151-2022-12-24" },
      WIKI_LIST,
    ],
  },

  /* ---------------- 2023 ---------------- */
  {
    id: "e2023-csbc",
    date: "2023-08-01",
    exam: "CSBC Bihar Police Prohibition Constable 2023",
    body: "Central Selection Board of Constable",
    state: "Bihar",
    region: "East",
    type: "Defence & police",
    status: "Cancelled & retest",
    scale: "Statewide cancellation after electronic answer keys circulated",
    summary: "Electronic copies of the answer keys were circulated across WhatsApp groups prior to exam shifts. CSBC cancelled the written exam for all candidates and conducted a statewide retest.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2023-rsmssb-patwari",
    date: "2023-12-01",
    exam: "RSMSSB Patwari 2023",
    body: "Rajasthan Staff Selection Board",
    state: "Rajasthan",
    region: "North",
    type: "Recruitment",
    status: "Cancelled & retest",
    scale: "Syndicate busted in Bharatpur; affected shifts cancelled",
    summary: "Police dismantled a leak syndicate operating in Bharatpur that had accessed examination sets. Compromised shifts were cancelled and re-tests were ordered for affected candidates.",
    sources: [WIKI_LIST],
  },

  /* ---------------- 2024 ---------------- */
  {
    id: "e2024-reet-level2",
    date: "2024-02-01",
    exam: "REET Level-2 2024 (Bharatpur leak)",
    body: "Board of Secondary Education, Rajasthan",
    state: "Rajasthan",
    region: "North",
    type: "Teacher eligibility",
    status: "Cancelled & retest",
    scale: "Localized paper leak; retest ordered for affected test centres",
    summary: "Breaches detected at testing centres in Bharatpur resulted in localized cancellations and re-examinations, marking another link in Rajasthan's recurring teacher recruitment challenges.",
    sources: [WIKI_LIST],
  },
  {
    id: "e2024-neet",
    date: "2024-05-05",
    exam: "NEET-UG 2024",
    body: "National Testing Agency",
    state: "All India",
    region: "All-India",
    type: "Medical entrance",
    status: "Probe ordered",
    scale: "24 lakh candidates; 67 perfect scores; 155 proven beneficiaries",
    summary: "Question papers leaked from a bank vault in Hazaribagh and were sold for ₹30–50 lakh in Patna. 67 candidates scored perfect 720/720. Supreme Court verified localized leaks but declined a nationwide retest.",
    detail: "The May 5, 2024 National Eligibility-cum-Entrance Test (NEET-UG) for 24 lakh medical aspirants erupted into India's biggest modern testing controversy when results declared on June 4 revealed an unprecedented 67 candidates securing a perfect 720/720 score, including clusters from single exam centres.\n\nInvestigations by Bihar Police Economic Offences Unit (EOU) and the CBI revealed that the question paper was stolen from an SBI bank vault in Hazaribagh, Jharkhand, by a syndicate that photographed the sheets and memorized them with students at a Patna play school for ₹30–50 lakh per candidate.\n\nThe Supreme Court of India conducted intensive hearings, confirming that while localized leaks and grace-mark anomalies had occurred, there was insufficient evidence of a systemic national breach to justify cancelling the entire exam for 24 lakh candidates.",
    keyFacts: [
      { k: "Candidate Base", v: "2.4 million medical aspirants across India" },
      { k: "Ground Zero", v: "Stolen from Oasis School / SBI Vault in Hazaribagh, Jharkhand" },
      { k: "Scoring Anomalies", v: "67 students initially scored perfect 720/720; revised after expert review" },
      { k: "Judicial Decision", v: "Supreme Court verified localized breach; declined full national cancellation" }
    ],
    sources: [
      { label: "Wikipedia — 2024 NEET controversy", url: "https://en.wikipedia.org/wiki/2024_NEET_controversy" },
      { label: "BBC News — How exam scandals taint India's most important exam (Jun 2024)", url: "https://www.bbc.com/news/articles/c511j589npyo" },
      { label: "The Hindu — Centre tells SC scrapping not rational (Jul 2024)", url: "https://www.thehindu.com/news/national/scrapping-neet-ug-2024-not-rational-will-jeopardise-interest-of-honest-candidates-centre-to-supreme-court/article68370662.ece" },
      { label: "ThePrint — the hole that wasn't plugged in 2024", url: "https://theprint.in/opinion/newsmaker-of-the-week/neet-paper-leak-came-from-a-hole-that-wasnt-plugged-in-2024-nta-is-ignoring-its-problems/2932680/" },
    ],
  },
  {
    id: "e2024-ugcnet",
    date: "2024-06-18",
    exam: "UGC-NET June 2024",
    body: "University Grants Commission / NTA",
    state: "All India",
    region: "All-India",
    type: "Professional",
    status: "Cancelled & retest",
    scale: "9 lakh candidates; cancelled 24 hours after completion",
    summary: "The Ministry of Education cancelled the national examination just 24 hours after completion when the Indian Cyber Crime Coordination Centre (I4C) confirmed the paper was circulating on the Darknet.",
    detail: "On June 18, 2024, over 9 lakh candidates took the UGC-NET exam across 1,205 centres in pen-and-paper OMR format. Within 24 hours, the Union Ministry of Education took the dramatic step of cancelling the entire national exam.\n\nInputs from the Ministry of Home Affairs' Indian Cyber Crime Coordination Centre (I4C) National Cyber Crime Threat Analytics Unit confirmed that the question paper was compromised and circulating on encrypted Telegram and Darknet channels prior to exam commencement.\n\nThe Union Education Minister accepted moral responsibility, removed the Director General of the National Testing Agency, and transferred the investigation to the CBI.",
    keyFacts: [
      { k: "Detection Agency", v: "Indian Cyber Crime Coordination Centre (I4C), MHA" },
      { k: "Cancellation Speed", v: "Cancelled nationwide within 24 hours of exam completion" },
      { k: "Administrative Fallout", v: "NTA Director General removed; high-level reform committee formed" }
    ],
    sources: [
      { label: "Indian Express — UGC-NET cancellation, NEET leak (Jun 2024)", url: "https://indianexpress.com/article/political-pulse/ugc-net-cancellation-neet-paper-leak-unease-sangh-abvp-people-questions-govt-answer-9404936/" },
      WIKI_LIST,
    ],
  },
  {
    id: "e2024-csir-net",
    date: "2024-06-21",
    exam: "CSIR-UGC NET & NEET-PG postponements 2024",
    body: "NTA / CSIR / NBEMS",
    state: "All India",
    region: "All-India",
    type: "Professional",
    status: "Cancelled & retest",
    scale: "Precautionary national postponement of multiple marquee exams",
    summary: "Following back-to-back breaches in NEET and UGC-NET, the Union Government postponed the Joint CSIR-UGC NET and NEET-PG as precautionary measures, enforcing the new anti-leak law.",
    sources: [
      { label: "ET Education — 2024: year of leaks, cancellations, protests", url: "https://education.economictimes.indiatimes.com/news/industry/2024-year-of-paper-leaks-test-cancellations-widespread-protests-and-exam-reforms/116888415" },
      WIKI_LIST,
    ],
  },
  {
    id: "e2024-bpsc-70",
    date: "2024-12-14",
    exam: "BPSC 70th Combined Prelims 2024",
    body: "Bihar Public Service Commission",
    state: "Bihar",
    region: "East",
    type: "Civil services",
    status: "Probe ordered",
    scale: "Re-examination ordered at affected Patna centre",
    summary: "Allegations of unsealed packets and question circulation during the 70th Combined Preliminary exam triggered student protests. BPSC ordered a re-examination for an affected Patna centre.",
    sources: [
      { label: "India Today — BPSC 70th leak claims (Dec 2024)", url: "https://www.indiatoday.in/education-today/news/story/bpsc-70th-cce-exampaper-leak-claims-chairman-denies-investigation-2649867-2024-12-14" },
      WIKI_LIST,
    ],
  },

  /* ---------------- 2026 ---------------- */
  {
    id: "e2026-neet",
    date: "2026-05-03",
    exam: "NEET-UG 2026",
    body: "National Testing Agency",
    state: "All India",
    region: "All-India",
    type: "Medical entrance",
    status: "Cancelled & retest",
    scale: "22.7 lakh candidates; 120/180 questions matched; Minister resigned",
    summary: "Commercial 'guess papers' matching 120 of 180 questions were reported sold for ₹2–10 lakh, allegedly fed by NTA translation insiders (per investigative reporting). The exam was cancelled on May 12, triggering historic protests and the reported resignation of the Union Education Minister.",
    detail: "The May 3, 2026 NEET-UG examination was compromised by an internal leak which, according to investigative reporting from the national press, originated within the NTA's confidential translation and moderation division, where a subject expert was alleged to have leaked complete question sets under the guise of commercial 'guess papers' reportedly sold for ₹2–10 lakh across multiple states.\n\nForensic comparison after the exam reportedly proved that 120 out of 180 questions matched the leaked sets verbatim. Following tragic reports of candidate suicides and escalating unrest, the Ministry of Education cancelled the examination on May 12, 2026.\n\nA re-test was conducted on June 21, 2026 with question papers transported under Indian Air Force security escort. Weeks of sustained student sit-ins at Jantar Mantar were reported to have culminated in the resignation of the Union Education Minister on July 25, 2026.",
    keyFacts: [
      { k: "Reported Forensic Evidence", v: "120 of 180 questions reportedly matched verbatim with leaked drafts" },
      { k: "Alleged Internal Source", v: "NTA translation and moderation insider syndicate (alleged, per reports)" },
      { k: "Reported Political Impact", v: "Union Education Minister reported to have resigned on July 25, 2026 following national protests" },
      { k: "Retest Security", v: "Papers transported via Indian Air Force aircraft under armed escort" }
    ],
    sources: [
      { label: "Wikipedia — 2026 NEET scandal", url: "https://en.wikipedia.org/wiki/2026_NEET_scandal" },
      { label: "Al Jazeera — What's next after Modi's promise on exam leaks (Jul 2026)", url: "https://www.aljazeera.com/news/2026/7/24/indian-student-protests-whats-next-after-modis-promise-on-exam-leaks" },
      { label: "The PIE News — From exam leaks to a national movement", url: "https://thepienews.com/from-exam-leaks-to-a-national-movement-inside-the-protests-reshaping-indias-education-debate/" },
    ],
  },
];

/* Protest documentation — used on the Protests page */
const PROTEST_ERAS = [
  {
    title: "The Vyapam Movement (2013–2015), Madhya Pradesh",
    text: "The Vyapam scandal—involving dozens of rigged recruitment and admission examinations—produced India's first sustained public campaigns against systemic recruitment fraud. Aspirants and parents mobilized for years before the Supreme Court transferred all cases to the Central Bureau of Investigation in 2015.",
    wiki: "https://en.wikipedia.org/wiki/Vyapam_scam",
  },
  {
    title: "SSC & Railway Aspirant Mobilization (2018–2022), New Delhi",
    text: "When the SSC CGL Tier-II answer keys were leaked online in 2018, tens of thousands of students occupied the CGO Complex in New Delhi for weeks. This movement laid the groundwork for the massive nationwide youth protests of 2021–2022 over recruitment freezes and technical malpractice in computer-based testing.",
    wiki: "https://en.wikipedia.org/wiki/List_of_paper_leaks_in_India",
  },
  {
    title: "The NEET & UGC-NET Uprising (2024), Nationwide",
    text: "The 2024 NEET-UG scoring anomalies and the overnight cancellation of UGC-NET brought lakhs of students to streets and public squares across New Delhi, Patna, Kota, and Kolkata. The pressure compelled the Union Government to notify the Public Examinations (Prevention of Unfair Means) Act, 2024 and replace the NTA leadership.",
    wiki: "https://en.wikipedia.org/wiki/2024_NEET_controversy",
  },
  {
    title: "Jantar Mantar & 'Sansad Chalo' (2026), New Delhi",
    text: "Following the cancellation of NEET-UG 2026, a youth-led coalition sustained a continuous sit-in at Jantar Mantar. Prominent civil society figures joined hunger strikes, and a 10,000-strong 'Sansad Chalo' march on July 20 demanded structural accountability, culminating in the resignation of the Union Education Minister on July 25, 2026.",
    wiki: "https://en.wikipedia.org/wiki/2026_NEET_scandal",
  },
];

/* Protest photographs — Wikimedia Commons, CC BY-SA 4.0, photographer Sumita Roy Dutta */
const PROTEST_IMAGES = [
  {
    file: "Students from All Over India protesting against 2026 NEET UG paper leak place Jantar Mantar on 20 July 2026 ahead of Parliament March 25.jpg",
    caption: "Students from across India assemble at Jantar Mantar, New Delhi, on 20 July 2026, ahead of the 'Sansad Chalo' march to Parliament over the NEET-UG 2026 paper leak.",
    credit: "Sumita Roy Dutta / Wikimedia Commons, CC BY-SA 4.0",
    wide: true,
  },
  {
    file: "Students from All Over India protesting against 2026 NEET UG paper leak place Jantar Mantar on 20 July 2026 ahead of Parliament March 02.jpg",
    caption: "Protesters demand systemic overhaul and independent judicial oversight of national testing agencies.",
    credit: "Sumita Roy Dutta / Wikimedia Commons, CC BY-SA 4.0",
  },
  {
    file: "Students from All Over India protesting against 2026 NEET UG paper leak place Jantar Mantar on 20 July 2026 ahead of Parliament March 08.jpg",
    caption: "Banners and placards documenting student grievances at Jantar Mantar, New Delhi.",
    credit: "Sumita Roy Dutta / Wikimedia Commons, CC BY-SA 4.0",
  },
  {
    file: "Students from All Over India protesting against 2026 NEET UG paper leak place Jantar Mantar on 20 July 2026 ahead of Parliament March 12.jpg",
    caption: "Student organizations from multiple states coordinate at the national demonstration ahead of the Parliament session.",
    credit: "Sumita Roy Dutta / Wikimedia Commons, CC BY-SA 4.0",
  },
  {
    file: "Students from All Over India protesting against 2026 NEET UG paper leak place Jantar Mantar on 20 July 2026 ahead of Parliament March 17.jpg",
    caption: "Demonstrators advance past initial security barricades near the Constitution Club during the July 2026 mobilization.",
    credit: "Sumita Roy Dutta / Wikimedia Commons, CC BY-SA 4.0",
  },
  {
    file: "Evening at Jantar Mantar Protest 21st July 2026.jpg",
    caption: "Candlelight vigils and sustained evening sit-ins at Jantar Mantar following the July 2026 demonstrations.",
    credit: "Alnitak-Alnilam-Mintaka / Wikimedia Commons, CC BY-SA 4.0",
  },
  {
    file: "Protest in LA to support Delhi Jantar Mantar protests, July 2026.jpg",
    caption: "Solidarity demonstration in Los Angeles, July 2026, reflecting global diaspora engagement with Indian educational reform.",
    credit: "Osparagus / Wikimedia Commons, CC BY-SA 4.0",
  },
];
